module Main in execution;

@Start
defun main (args : String[]) : void
{
    val t = new Throwable(); 

    try
    {
        F::rethrow(t);

        F::println("The exception was not thrown.");
    }
    catch(ex : CheckedException)
    {
        F::println("The exception was thrown.");
    }
}
