module Main in execution;

@Start
defun main (args : String[]) : void
{
    try
    {
        Main::trouble();

        assert false;
    }
    catch (ex : RuntimeException)
    {
        assert true;
    }
}

defun trouble () : void
{
    try
    {
        # This exception should propagate to the try-catch in main().
        throw new IllegalStateException();

        assert false;
    }
    catch (ex : NullPointerException)
    {
        assert false;
    }
}