module Main in examples;

exception Apocalypse extends RuntimeException;

exception Apophis99942 extends Apocalypse;

@Start
defun main (args : String[]) : void
{
    try
    {
        F::println("Oh look, a meteor?");

        throw new Apophis99942("Oh no, an asteroid!");

        F::println("The world survived!");
    }
    catch (problem : Apocalypse)
    {
        F::println(problem.getMessage());
        F::println("Ah well, back to the stone age.");
    }
}



 

