{ "summary" : "This function throws the exception that it is given as an argument.", "signature" : "raise (exception : <a href='https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html'>Throwable</a>) : void", "formals" : [["exception", "class java.lang.Throwable", "is the exception to throw."]], "returns" : ["void", "This function does not return, because the <i>exception</i> is thrown."], "throws" : [["<a href='https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html'>Throwable</a>", "in order to be capable of throwing any type of exception."], ["<a href='https://docs.oracle.com/javase/7/docs/api/java/lang/NullPointerException.html'>NullPointerException</a>", "if <i>exception</i> is null."]], "details" : [], "example-1" : ["module Main in execution;%0A%0A@Start%0Adefun main (args : String[]) : void%0A{%0A    val t = new RuntimeException(); %0A%0A    try%0A    {%0A        F::raise(t);%0A%0A        F::println(%22The exception was not thrown.%22);%0A    }%0A    catch(ex : RuntimeException)%0A    {%0A        F::println(%22The exception was thrown.%22);%0A    }%0A}", ""] }